//Array containing the demo data that is rendered inside the Rewards Table 
export const RewardService = {
    getRewardsData() {
        return [
                {
                  id: 1,
                  name: "Bierens Superhero Poster",
                  tier: 1,
                  season: "Autumn",
                  quantity: 50,
                  type: "Physical",
                  action: "Edit",
                  image: '/dummyimage.png',
                  description: 'Reward Description',
                },
                {
                  id: 2,
                  name: "Retro Marvel Comics",
                  tier: 1,
                  season: "Autumn",
                  quantity: 20,
                  type: "Physical",
                  action: "Edit",
                  image: '/dummyimage.png',
                  description: 'Reward Description',
                },
                {
                  id: 3,
                  name: "Gift Card",
                  tier: 2,
                  season: "Autumn",
                  quantity: 30,
                  type: "Digital",
                  action: "Edit",
                  image: '/dummyimage.png',
                  description: 'Reward Description',
                },
                {
                  id: 4,
                  name: "Book 'Atomic Habits'",
                  tier: 2,
                  season: "Autumn",
                  quantity: 25,
                  type: "Physical",
                  action: "Edit",
                  image: '/dummyimage.png',
                  description: 'Reward Description',
                },
                {
                  id: 5,
                  name: "Extreme Experience",
                  tier: 3,
                  season: "Autumn",
                  quantity: 15,
                  type: "Physical",
                  action: "Edit",
                  image: '/dummyimage.png',
                  description: 'Reward Description',
                },
                {
                  id: 6,
                  name: "Udemy Course",
                  tier: 3,
                  season: "Autumn",
                  quantity: 30,
                  type: "Digital",
                  action: "Edit",
                  image: '/dummyimage.png',
                  description: 'Reward Description',

                },
                {
                  id: 7,
                  name: "Company Dinner",
                  tier: 4,
                  season: "Autumn",
                  quantity: 5,
                  type: "Physical",
                  action: "Edit",
                  image: '/dummyimage.png',
                  description: 'Reward Description',

                },
                {
                  id: 8,
                  name: "Retro Jukebox",
                  tier: 4,
                  season: "Autumn",
                  quantity: 5,
                  type: "Physical",
                  action: "Edit",
                  image: '/dummyimage.png',
                  description: 'Reward Description',

                },
                {
                  id: 9,
                  name: "Bierens Event",
                  tier: 5,
                  season: "Autumn",
                  quantity: 2,
                  type: "Physical",
                  action: "Edit",
                  image: '/dummyimage.png',
                  description: 'Reward Description',

                },
                {
                  id: 10,
                  name: "Gift Card",
                  tier: 2,
                  season: "Winter",
                  quantity: 25,
                  type: "Digital",
                  action: "Edit",
                  image: '/dummyimage.png',
                  description: 'Reward Description',

                },
                {
                  id: 11,
                  name: "Book 'What To Eat When?'",
                  tier: 2,
                  season: "Winter",
                  quantity: 55,
                  type: "Physical",
                  action: "Edit",
                  image: '/dummyimage.png',
                  description: 'Reward Description',

                },
                {
                  id: 12,
                  name: "Company Party",
                  tier: 3,
                  season: "Winter",
                  quantity: 20,
                  type: "Physical",
                  action: "Edit",
                  image: '/dummyimage.png',
                  description: 'Reward Description',

                },
                {
                  id: 13,
                  name: "Cinema Tickets",
                  tier: 3,
                  season: "Winter",
                  quantity: 20,
                  type: "Digital",
                  action: "Edit",
                  image: '/dummyimage.png',
                  description: 'Reward Description',

                },
                {
                  id: 14,
                  name: "Holiday Voucher",
                  tier: 4,
                  season: "Winter",
                  quantity: 15,
                  type: "Digital",
                  action: "Edit",
                  image: '/dummyimage.png',
                  description: 'Reward Description',

                },
                {
                  id: 15,
                  name: "Retro Vinyl Player",
                  tier: 4,
                  season: "Winter",
                  quantity: 5,
                  type: "Physical",
                  action: "Edit",
                  image: '/dummyimage.png',
                  description: 'Reward Description',

                },
                {
                  id: 16,
                  name: "Bierens Christmas Party",
                  tier: 5,
                  season: "Winter",
                  quantity: 15,
                  type: "Physical",
                  action: "Edit",
                  image: '/dummyimage.png',
                  description: 'Reward Description',

                },
                {
                  id: 17,
                  name: "Bierens Coolbox",
                  tier: 1,
                  season: "Summer",
                  quantity: 20,
                  type: "Physical",
                  action: "Edit",
                  image: '/dummyimage.png',
                  description: 'Reward Description',

                },
                {
                  id: 18,
                  name: "Bierens Summer Towel",
                  tier: 1,
                  season: "Summer",
                  quantity: 10,
                  type: "Physical",
                  action: "Edit",
                  image: '/dummyimage.png',
                  description: 'Reward Description',

                },
                {
                  id: 19,
                  name: "Sunscreen Spray",
                  tier: 2,
                  season: "Summer",
                  quantity: 15,
                  type: "Physical",
                  action: "Edit",
                  image: '/dummyimage.png',
                  description: 'Reward Description',

                },
                {
                  id: 20,
                  name: "Bierens Air Mattress",
                  tier: 2,
                  season: "Summer",
                  quantity: 25,
                  type: "Physical",
                  action: "Edit",
                  image: '/dummyimage.png',
                  description: 'Reward Description',

                },
                {
                  id: 21,
                  name: "Company Pool Party",
                  tier: 3,
                  season: "Summer",
                  quantity: 13,
                  type: "Physical",
                  action: "Edit",
                  image: '/dummyimage.png',
                  description: 'Reward Description',

                },
                {
                  id: 22,
                  name: "Bierens Summer Glasses",
                  tier: 3,
                  season: "Summer",
                  quantity: 16,
                  type: "Physical",
                  action: "Edit",
                  image: '/dummyimage.png',
                  description: 'Reward Description',

                },
                {
                  id: 23,
                  name: "Polaroid",
                  tier: 4,
                  season: "Summer",
                  quantity: 5,
                  type: "Physical",
                  action: "Edit",
                  image: '/dummyimage.png',
                  description: 'Reward Description',

                },
                {
                  id: 24,
                  name: "Summer Voucher",
                  tier: 4,
                  season: "Summer",
                  quantity: 50,
                  type: "Digital",
                  action: "Edit",
                  image: '/dummyimage.png',
                  description: 'Reward Description',

                },
                {
                  id: 25,
                  name: "Bierens Summer Party",
                  tier: 5,
                  season: "Summer",
                  quantity: 5,
                  type: "Physical",
                  action: "Edit",
                  image: '/dummyimage.png',
                  description: 'Reward Description',

                },
                {
                  id: 26,
                  name: "Bierens Eastern Basket",
                  tier: 1,
                  season: "Spring",
                  quantity: 29,
                  type: "Physical",
                  action: "Edit",
                  image: '/dummyimage.png',
                  description: 'Reward Description',

                },
                {
                  id: 27,
                  name: "Spring Shirt",
                  tier: 1,
                  season: "Spring",
                  quantity: 23,
                  type: "Physical",
                  action: "Edit",
                  image: '/dummyimage.png',
                  description: 'Reward Description',

                },
                {
                  id: 28,
                  name: "Gift Card",
                  tier: 2,
                  season: "Spring",
                  quantity: 55,
                  type: "Digital",
                  action: "Edit",
                  image: '/dummyimage.png',
                  description: 'Reward Description',

                },
                {
                  id: 29,
                  name: "Decor Plant",
                  tier: 2,
                  season: "Spring",
                  quantity: 65,
                  type: "Physical",
                  action: "Edit",
                  image: '/dummyimage.png',
                  description: 'Reward Description',

                },
                {
                  id: 30,
                  name: "Skill Share Course",
                  tier: 3,
                  season: "Spring",
                  quantity: 28,
                  type: "Digital",
                  action: "Edit",
                  image: '/dummyimage.png',
                  description: 'Reward Description',
                },
                {
                  id: 31,
                  name: "Perfume",
                  tier: 3,
                  season: "Spring",
                  quantity: 47,
                  type: "Physical",
                  action: "Edit",
                  image: '/dummyimage.png',
                  description: 'Reward Description',

                },
                {
                  id: 32,
                  name: "Company Dinner",
                  tier: 4,
                  season: "Spring",
                  quantity: 3,
                  type: "Physical",
                  action: "Edit",
                  image: '/dummyimage.png',
                  description: 'Reward Description',

                },
                {
                  id: 33,
                  name: "Retro Walkman",
                  tier: 4,
                  season: "Spring",
                  quantity: 23,
                  type: "Physical",
                  action: "Edit",
                  image: '/dummyimage.png',
                  description: 'Reward Description',
                },
                {
                  id: 34,
                  name: "Bierens Easter Party",
                  tier: 5,
                  season: "Spring",
                  quantity: 2,
                  type: "Physical",
                  action: "Edit",
                  description: 'Reward Description',
                  image: '/dummyimage.png',
                }
        ];
    },

    getRewardsMini() {
        return Promise.resolve(this.getRewardsData().slice(0, 5));
    },

    getRewardsSmall() {
        return Promise.resolve(this.getRewardsData().slice(0, 10));
    },

    getRewards() {
        return Promise.resolve(this.getRewardsData());
    },

    getRewardsWithOrdersSmall() {
        return Promise.resolve(this.getRewardsWithOrdersData().slice(0, 10));
    },

    getRewardsWithOrders() {
        return Promise.resolve(this.getRewardsWithOrdersData());
    }
};

